insert into main.User (username, firstname, lastname, passhash, email, lastlogin) values 
('mhaskell','Michael', 'Haskell', '', 'mhaskell@calpoly.edu', ''),
('testuser1','Test', 'User1', '', 'testuser1@calpoly.edu', ''),
('root', 'root', 'root', 'B81E8CEA477D0AE95CFB0994297189F92E093BBA598690BE0CCEB085E90FFA1E0A1D32F1B44C50B8E0BFFC3F4896BEA735165E430D3475FA324B61BBC81643F8', 'root@calpoly.edu', '');
insert into ProTeam (name, league) values 
('Roma', 'Serie A'),
('Bayern Munich', 'Bundesliga'),
('FC Barcelona', 'La Liga'),
('Real Madrid', 'La Liga'),
('Atletico Madrid', 'La Liga'),
('PSG', 'United Football League'),
('Arsenal', 'Premier League'),
('Manchester United', 'Premier League'),
('Manchester City', 'Premier League'),
('Leicester City', 'Premier League'),
('Liverpool', 'Premier League'),
('Chelsea', 'Premier League');
insert into ProPlayer (team, name, position, number) values
('Roma', 'Bogdan Lobont', 'G', 1),
('Roma', 'Wojciech Szczesny', 'G', 25),
('Roma', 'Morgan De Sanctis', 'G', 26),
('Roma', 'Ionut Pop', 'G', 59),
('Roma', 'Lorenzo Cristanto', 'G', 98),
('Roma', 'Antonio Rüdiger', 'D', 2),
('Roma', 'Lucas Digne', 'D', 3),
('Roma', 'Radja Nainggolan', 'M', 4),
('Roma', 'Leandro Castan', 'D', 5),
('Roma', 'Kevin Strootman', 'M', 6),
('Roma', 'Diego Perotti', 'M', 8),
('Roma', 'Edin Dzeko', 'F', 9),
('Roma', 'Francesco Totti', 'F', 10),
('Roma', 'Mohamed Salah', 'M', 11),
('Roma', 'Maicon', 'D', 13),
('Roma', 'Iago Falqué', 'F', 14),
('Roma', 'Miralem Pjanic', 'M', 15),
('Roma', 'Daniele de Rossi', 'M', 16),
('Roma', 'Ezequiel Ponce', 'F', 18),
('Roma', 'Seydou Keita', 'M', 20),
('Roma', 'William Vainqueur', 'M', 21),
('Roma', 'Stephan El Shaarawy', 'F', 22),
('Roma', 'Norbert Gyömbér', 'D', 23),
('Roma', 'Alessandro Florenzi', 'M', 24),
('Roma', 'Emerson', 'D', 33),
('Roma', 'Vasileios Torosidis', 'D', 35),
('Roma', 'Kostas Manolas', 'D', 44),
('Roma', 'Salih Ucan', 'M', 48),
('Roma', 'Silvio Anocic', 'D', 51),
('Roma', 'Lorenzo Di Livio', 'M', 52),
('Roma', 'Christian D''Urso', 'M', 53),
('Roma', 'Eros De Santis', 'D', 55),
('Roma', 'Jose Machin Dicombo', 'M', 57),
('Roma', 'Ervin Zukanovic', 'D', 87),
('Roma', 'Riccardo Marchizza', 'D', 91),
('Roma', 'Edoardo Soleri', 'F', 92),
('Roma', 'Marco Tumminello', 'F', 93),
('Roma', 'Elio Capradossi', 'D', 95),
('Roma', 'Sadiq Umar', 'F', 97),
('Roma', 'Nura Abdullahi', 'D', 99),
('Bayern Munich', 'Ivan Lucic', 'G', 33),
('Bayern Munich', 'Manuel Neuer', 'G', 1),
('Bayern Munich', 'Tom Starke', 'G', 22),
('Bayern Munich', 'Sven Ulreich', 'G', 26),
('Bayern Munich', 'David Alaba', 'D', 27),
('Bayern Munich', 'Holger Badstuber', 'D', 28),
('Bayern Munich', 'Medhi Benatia', 'D', 5),
('Bayern Munich', 'Juan Bernat', 'D', 18),
('Bayern Munich', 'Jérome Boateng', 'D', 17),
('Bayern Munich', 'Rafinha', 'D', 13),
('Bayern Munich', 'Philipp Lahm', 'D', 21),
('Bayern Munich', 'Philipp Steinhart', 'D', 39),
('Bayern Munich', 'Serdar Tasci', 'D', 4),
('Bayern Munich', 'Thiago Alcantara', 'M', 6),
('Bayern Munich', 'Xabi Alonso', 'M', 14),
('Bayern Munich', 'Fabian Benko', 'M', 40),
('Bayern Munich', 'Kingsley Coman', 'M', 29),
('Bayern Munich', 'Julian Green', 'M', 37),
('Bayern Munich', 'Mario Götze', 'M', 19),
('Bayern Munich', 'Joshua Kimmich', 'M', 32),
('Bayern Munich', 'Javi Martínez', 'M', 8),
('Bayern Munich', 'Franck Ribéry', 'M', 7),
('Bayern Munich', 'Arjen Robben', 'M', 10),
('Bayern Munich', 'Sebastian Rode', 'M', 20),
('Bayern Munich', 'Arturo Vidal', 'M', 23),
('Bayern Munich', 'Douglas Costa', 'F', 11),
('Bayern Munich', 'Robert Lewandowski', 'F', 9),
('Bayern Munich', 'Thomas Müller', 'F', 25),
('Bayern Munich', 'Milos Pantovic', 'F', 41),
('Bayern Munich', 'Patrick Weihrauch', 'F', 36),
('Real Madrid', 'Kiko Casilla', 'G', 13),
('Real Madrid', 'Keylor Navas', 'G', 1),
('Real Madrid', 'Rubén Yáñez', 'G', 31),
('Real Madrid', 'Álvaro Arbeloa', 'D', 17),
('Real Madrid', 'Daniel Carvajal', 'D', 15),
('Real Madrid', 'Nacho', 'D', 6),
('Real Madrid', 'Philipp Lienhart', 'D', 32),
('Real Madrid', 'Pepe', 'D', 3),
('Real Madrid', 'Sergio Ramos', 'D', 4),
('Real Madrid', 'Tejero', 'D', 34),
('Real Madrid', 'Raphaël Varane', 'D', 2),
('Real Madrid', 'Marcelo', 'D', 12),
('Real Madrid', 'Danilo', 'D', 23),
('Real Madrid', 'Isco', 'M', 22),
('Real Madrid', 'Casemiro', 'M', 14),
('Real Madrid', 'Mateo Kovacic', 'M', 16),
('Real Madrid', 'Toni Kroos', 'M', 8),
('Real Madrid', 'Lazo', 'M', 33),
('Real Madrid', 'Marcos Llorente', 'M', 28),
('Real Madrid', 'Luka Modric', 'M', 19),
('Real Madrid', 'Martin Odegaard', 'M', 27),
('Real Madrid', 'James Rodríguez', 'M', 10),
('Real Madrid', 'Lucas Vázquez', 'M', 18),
('Real Madrid', 'Gareth Bale', 'F', 11),
('Real Madrid', 'Karim Benzema', 'F', 9),
('Real Madrid', 'Borja Mayoral', 'F', 29),
('Real Madrid', 'Jesé', 'F', 20),
('Real Madrid', 'Cristiano Ronaldo', 'F', 7),
('FC Barcelona', 'Claudio Bravo', 'G', 13),
('FC Barcelona', 'Jordi Masip', 'G', 25),
('FC Barcelona', 'Marc-André ter Stegen', 'G', 1),
('FC Barcelona', 'Jordi Alba', 'D', 18),
('FC Barcelona', 'Marc Bartra', 'D', 15),
('FC Barcelona', 'Adriano', 'D', 21),
('FC Barcelona', 'Douglas', 'D', 2),
('FC Barcelona', 'Javier Mascherano', 'D', 14),
('FC Barcelona', 'Jérémy Mathieu', 'D', 24),
('FC Barcelona', 'Gerard Piqué', 'D', 3),
('FC Barcelona', 'Thomas Vermaelen', 'D', 23),
('FC Barcelona', 'Aleix Vidal', 'D', 22),
('FC Barcelona', 'Dani Alves', 'D', 6),
('FC Barcelona', 'Rafinha', 'M', 12),
('FC Barcelona', 'Carlos Aleñá', 'M', 37),
('FC Barcelona', 'Sergio Busquets', 'M', 5),
('FC Barcelona', 'Cámara', 'M', 27),
('FC Barcelona', 'Gerard', 'M', 28),
('FC Barcelona', 'Andrés Iniesta', 'M', 8),
('FC Barcelona', 'Wilfrid Kaptoum', 'M', 34),
('FC Barcelona', 'Ivan Rakitic', 'M', 4),
('FC Barcelona', 'Sergi Roberto', 'M', 20),
('FC Barcelona', 'Sergi Samper', 'M', 26),
('FC Barcelona', 'Arda Turan', 'M', 7),
('FC Barcelona', 'Munir El Haddadi', 'F', 17),
('FC Barcelona', 'Lionel Messi', 'F', 10),
('FC Barcelona', 'Sandro Ramírez', 'F', 19),
('FC Barcelona', 'Daniel Romera', 'F', 36),
('FC Barcelona', 'Luis Suárez', 'F', 9),
('FC Barcelona', 'Neymar', 'F', 11),
('Atletico Madrid', 'Miguel Ángel Moyá', 'G', 1),
('Atletico Madrid', 'Jan Oblak', 'G', 13),
('Atletico Madrid', 'José Giménez', 'D', 24),
('Atletico Madrid', 'Diego Godín', 'D', 2),
('Atletico Madrid', 'Borja González', 'D', 27),
('Atletico Madrid', 'Jesús Gámez', 'D', 18),
('Atletico Madrid', 'Lucas Hernández', 'D', 19),
('Atletico Madrid', 'Theo Hernández', 'D', 33),
('Atletico Madrid', 'Filipe Luís', 'D', 3),
('Atletico Madrid', 'Ignacio Monsalve', 'D', 32),
('Atletico Madrid', 'Stefan Savic', 'D', 15),
('Atletico Madrid', 'Juanfran', 'D', 20),
('Atletico Madrid', 'Tiago', 'M', 5),
('Atletico Madrid', 'Gabi', 'M', 14),
('Atletico Madrid', 'Augusto Fernández', 'M', 12),
('Atletico Madrid', 'Yannick Ferreira-Carrasco', 'M', 21),
('Atletico Madrid', 'Matias Kranevitter', 'M', 8),
('Atletico Madrid', 'Koke', 'M', 6),
('Atletico Madrid', 'Thomas', 'M', 22),
('Atletico Madrid', 'Óliver', 'M', 10),
('Atletico Madrid', 'Saúl Ñíguez', 'M', 17),
('Atletico Madrid', 'Ángel Correa', 'F', 16),
('Atletico Madrid', 'Amath Amath Diedhiou', 'F', 35),
('Atletico Madrid', 'Antoine Griezmann', 'F', 7),
('Atletico Madrid', 'Roberto Núñez', 'F', 28),
('Atletico Madrid', 'Fernando Torres', 'F', 9),
('Atletico Madrid', 'Luciano Vietto', 'F', 23),
('Atletico Madrid', 'Samuel Villa', 'F', 34),
('PSG', 'Rémy Descamps', 'G', '--'),
('PSG', 'Nicolas Douchez', 'G', 1),
('PSG', 'Salvatore Sirigu', 'G', 30),
('PSG', 'Kevin Trapp', 'G', 16),
('PSG', 'Marquinhos', 'D', 5),
('PSG', 'Serge Aurier', 'D', 19),
('PSG', 'Alec Georgen', 'D', '--'),
('PSG', 'Presnel Kimpembe', 'D', 3),
('PSG', 'Layvin Kurzawa', 'D', 20),
('PSG', 'David Luiz', 'D', 32),
('PSG', 'Kevin Rimane', 'D', '--'),
('PSG', 'Maxwell', 'D', 17),
('PSG', 'Thiago Silva', 'D', 2),
('PSG', 'Gregory Van Der Wiel', 'D', 23),
('PSG', 'Jean-Kevin Augustin', 'M', 29),
('PSG', 'Ángel Di María', 'M', 11),
('PSG', 'Mamadou Doucoure', 'M', '--'),
('PSG', 'Blaise Matuidi', 'M', 14),
('PSG', 'Thiago Motta', 'M', 8),
('PSG', 'Christopher Nkunku', 'M', '--'),
('PSG', 'Javier Pastore', 'M', 27),
('PSG', 'Adrien Rabiot', 'M', 25),
('PSG', 'Benjamin Stambouli', 'M', 4),
('PSG', 'Marco Verratti', 'M', 6),
('PSG', 'Meite Yakou', 'M', '--'),
('PSG', 'Edinson Cavani', 'F', 9),
('PSG', 'Zlatan Ibrahimovic', 'F', 10),
('PSG', 'Lucas Moura', 'F', 7),
('PSG', 'Hervin Ongenda', 'F', 35),
('PSG', 'Timothée Taufflieb', 'F', '--'),
('Arsenal', 'Petr Cech', 'G', 33),
('Arsenal', 'Matthew Macey', 'G', 49),
('Arsenal', 'David Ospina', 'G', 13),
('Arsenal', 'Hector Bellerin', 'D', 24),
('Arsenal', 'Calum Chambers', 'D', 21),
('Arsenal', 'Kieran Gibbs', 'D', 3),
('Arsenal', 'Carl Jenkinson', 'D', 25),
('Arsenal', 'Laurent Koscielny', 'D', 6),
('Arsenal', 'Per Mertesacker', 'D', 4),
('Arsenal', 'Nacho Monreal', 'D', 18),
('Arsenal', 'Gabriel Paulista', 'D', 5),
('Arsenal', 'Mikel Arteta', 'M', 8),
('Arsenal', 'Ismael Bennacer', 'M', 36),
('Arsenal', 'Krystian Bielik', 'M', 37),
('Arsenal', 'Santi Cazorla', 'M', 19),
('Arsenal', 'Francis Coquelin', 'M', 34),
('Arsenal', 'Mohamed Elneny', 'M', 35),
('Arsenal', 'Mathieu Flamini', 'M', 20),
('Arsenal', 'Serge Gnabry', 'M', 27),
('Arsenal', 'Alex Iwobi', 'M', 45),
('Arsenal', 'Alex Oxlade-Chamberlain', 'M', 15),
('Arsenal', 'Aaron Ramsey', 'M', 16),
('Arsenal', 'Tomas Rosicky', 'M', 7),
('Arsenal', 'Ben Sheaf', 'M', 56),
('Arsenal', 'Chris Willock', 'M', 59),
('Arsenal', 'Jack Wilshere', 'M', 10),
('Arsenal', 'Mesut Özil', 'M', 11),
('Arsenal', 'Joel Campbell', 'F', 28),
('Arsenal', 'Olivier Giroud', 'F', 12),
('Arsenal', 'Jeff Reine-Adelaide', 'F', 54),
('Arsenal', 'Alexis Sánchez', 'F', 17),
('Arsenal', 'Theo Walcott', 'F', 14),
('Arsenal', 'Danny Welbeck', 'F', 23),
('Manchester United', 'Joel Castro', 'G', 40),
('Manchester United', 'David De Gea', 'G', 1),
('Manchester United', 'Sam Johnstone', 'G', 50),
('Manchester United', 'Sergio Romero', 'G', 20),
('Manchester United', 'Daley Blind', 'D', 17),
('Manchester United', 'Cameron Borthwick-Jackson', 'D', 43),
('Manchester United', 'Matteo Darmian', 'D', 36),
('Manchester United', 'Timothy Fosu-Mensah', 'D', 51),
('Manchester United', 'Phil Jones', 'D', 4),
('Manchester United', 'Donald Love', 'D', 37),
('Manchester United', 'Patrick McNair', 'D', 33),
('Manchester United', 'Marcos Rojo', 'D', 5),
('Manchester United', 'Luke Shaw', 'D', 23),
('Manchester United', 'Chris Smalling', 'D', 12),
('Manchester United', 'Axel Tuanzebe', 'D', 38),
('Manchester United', 'Antonio Valencia', 'D', 25),
('Manchester United', 'Gullermo Varela', 'D', 30),
('Manchester United', 'Ro-Shaun Williams', 'D', '--'),
('Manchester United', 'Michael Carrick', 'M', 16),
('Manchester United', 'Marouane Fellaini', 'M', 27),
('Manchester United', 'Sean Goss', 'M', 45),
('Manchester United', 'Ander Herrera', 'M', 21),
('Manchester United', 'Adnan Januzaj', 'M', 11),
('Manchester United', 'Jesse Lingard', 'M', 35),
('Manchester United', 'Juan Mata', 'M', 8),
('Manchester United', 'Andreas Pereira', 'M', 44),
('Manchester United', 'Regan Poole', 'M', 41),
('Manchester United', 'Joe Riley', 'M', 49),
('Manchester United', 'Joe Rothwell', 'M', 46),
('Manchester United', 'Morgan Schneiderlin', 'M', 28),
('Manchester United', 'Bastian Schweinsteiger', 'M', 31),
('Manchester United', 'James Weir', 'M', 47),
('Manchester United', 'Ashley Young', 'M', 18),
('Manchester United', 'Memphis Depay', 'F', 7),
('Manchester United', 'William Keane', 'F', 48),
('Manchester United', 'Anthony Martial', 'F', 9),
('Manchester United', 'Marcus Rashford', 'F', 39),
('Manchester United', 'Wayne Rooney', 'F', 10),
('Manchester City', 'Wilfredo Caballero', 'G', 13),
('Manchester City', 'Joe Hart', 'G', 1),
('Manchester City', 'Richard Wright', 'G', 29),
('Manchester City', 'Oluwatosin Adarabioyo', 'D', 53),
('Manchester City', 'Gaël Clichy', 'D', 22),
('Manchester City', 'Martín Demichelis', 'D', 26),
('Manchester City', 'Angeliño', 'D', 69),
('Manchester City', 'Cameron Humphreys', 'D', 77),
('Manchester City', 'Aleksandar Kolarov', 'D', 11),
('Manchester City', 'Vincent Kompany', 'D', 4),
('Manchester City', 'Eliaquim Mangala', 'D', 20),
('Manchester City', 'Nicolás Otamendi', 'D', 30),
('Manchester City', 'Bacary Sagna', 'D', 3),
('Manchester City', 'Pablo Zabaleta', 'D', 5),
('Manchester City', 'Brandon Barker', 'M', 62),
('Manchester City', 'Bersant Celina', 'M', 59),
('Manchester City', 'Kevin De Bruyne', 'M', 17),
('Manchester City', 'Fabian Delph', 'M', 18),
('Manchester City', 'Aleix Garciá Serrano', 'M', 75),
('Manchester City', 'Manu García', 'M', 76),
('Manchester City', 'George Glendon', 'M', 73),
('Manchester City', 'James Horsfield', 'M', 61),
('Manchester City', 'Samir Nasri', 'M', 8),
('Manchester City', 'Jesús Navas', 'M', 15),
('Manchester City', 'Fernando', 'M', 6),
('Manchester City', 'Fernandinho', 'M', 25),
('Manchester City', 'David Silva', 'M', 21),
('Manchester City', 'Yaya Touré', 'M', 42),
('Manchester City', 'Sergio Agüero', 'F', 10),
('Manchester City', 'Wilfried Bony', 'F', 14),
('Manchester City', 'David Faupala', 'F', 51),
('Manchester City', 'Kelechi Iheanacho', 'F', 72),
('Manchester City', 'Raheem Sterling', 'F', 7),
('Leicister City', 'Ben Hamer', 'G', 12),
('Leicister City', 'Jonathan Maddison', 'G', 41),
('Leicister City', 'Kasper Schmeichel', 'G', 1),
('Leicister City', 'Mark Schwarzer', 'G', 32),
('Leicister City', 'Benjamin Chilwell', 'D', 30),
('Leicister City', 'Christian Fuchs', 'D', 28),
('Leicister City', 'Robert Huth', 'D', 6),
('Leicister City', 'Liam Moore', 'D', 18),
('Leicister City', 'Wes Morgan', 'D', 5),
('Leicister City', 'Danny Simpson', 'D', 17),
('Leicister City', 'Marcin Wasilewski', 'D', 27),
('Leicister City', 'Marc Albrighton', 'M', 11),
('Leicister City', 'Daniel Amartey', 'M', 13),
('Leicister City', 'Daniel Drinkwater', 'M', 4),
('Leicister City', 'Nathan Dyer', 'M', 24),
('Leicister City', 'Gokhan Inler', 'M', 33),
('Leicister City', 'Matthew James', 'M', 8),
('Leicister City', 'N''Golo Kanté', 'M', 14),
('Leicister City', 'Andy King', 'M', 10),
('Leicister City', 'Riyad Mahrez', 'M', 26),
('Leicister City', 'Andre Olukanmi', 'M', 39),
('Leicister City', 'Jefferey Schlupp', 'M', 15),
('Leicister City', 'Joseph Dodoo', 'F', 36),
('Leicister City', 'Demarai Gray', 'F', 22),
('Leicister City', 'Shinji Okazaki', 'F', 20),
('Leicister City', 'Leonardo Ulloa', 'F', 23),
('Leicister City', 'Jamie Vardy', 'F', 9),
('Liverpool', 'Adam Bogdan', 'G', 34),
('Liverpool', 'Simon Mignolet', 'G', 22),
('Liverpool', 'Danny Ward', 'G', 52),
('Liverpool', 'Steven Caulker', 'D', 19),
('Liverpool', 'Daniel Cleary', 'D', 58),
('Liverpool', 'Nathaniel Clyne', 'D', 2),
('Liverpool', 'Jon Flanagan', 'D', 38),
('Liverpool', 'Joseph Gomez', 'D', 12),
('Liverpool', 'Tiago Ilori', 'D', 26),
('Liverpool', 'Dejan Lovren', 'D', 6),
('Liverpool', 'Joseph Maguire', 'D', 57),
('Liverpool', 'Conor Masterson', 'D', 87),
('Liverpool', 'Alberto Moreno', 'D', 18),
('Liverpool', 'Connor Randall', 'D', 56),
('Liverpool', 'Mamadou Sakho', 'D', 17),
('Liverpool', 'Martin Skrtel', 'D', 37),
('Liverpool', 'Brad Smith', 'D', 44),
('Liverpool', 'Kevin Stewart', 'D', 35),
('Liverpool', 'José Enrique', 'D', 3),
('Liverpool', 'Kolo Touré', 'D', 4),
('Liverpool', 'Joe Allen', 'M', 24),
('Liverpool', 'Cameron Brannagan', 'M', 32),
('Liverpool', 'Emre Can', 'M', 23),
('Liverpool', 'Pedro Chirivella', 'M', 68),
('Liverpool', 'Philippe Coutinho', 'M', 10),
('Liverpool', 'Jordan Henderson', 'M', 14),
('Liverpool', 'Jordon Ibe', 'M', 33),
('Liverpool', 'Ryan Kent', 'M', 40),
('Liverpool', 'Adam Lallana', 'M', 20),
('Liverpool', 'James Milner', 'M', 7),
('Liverpool', 'Sheyi Ojo', 'M', 54),
('Liverpool', 'Lucas', 'M', 21),
('Liverpool', 'Jordan Rossiter', 'M', 46),
('Liverpool', 'Joao Carlos Teixeira', 'M', 53),
('Liverpool', 'Roberto Firmino', 'F', 11),
('Liverpool', 'Christian Benteke', 'F', 9),
('Liverpool', 'Danny Ings', 'F', 28),
('Liverpool', 'Divock Origi', 'F', 27),
('Liverpool', 'Jerome Sinclair', 'F', 48),
('Liverpool', 'Daniel Sturridge', 'F', 15),
('Chelsea', 'Marco Amelia', 'G', 32),
('Chelsea', 'Asmir Begovic', 'G', 1),
('Chelsea', 'Thibaut Courtois', 'G', 13),
('Chelsea', 'Ola Aina', 'D', 34),
('Chelsea', 'César Azpilicueta', 'D', 28),
('Chelsea', 'Gary Cahill', 'D', 24),
('Chelsea', 'Jake Clark-Salter', 'D', 37),
('Chelsea', 'Branislav Ivanovic', 'D', 2),
('Chelsea', 'Matt Miazga', 'D', 20),
('Chelsea', 'Baba Rahman', 'D', 6),
('Chelsea', 'John Terry', 'D', 26),
('Chelsea', 'Kurt Zouma', 'D', 5),
('Chelsea', 'Charlie Colkett', 'M', 41),
('Chelsea', 'Willian', 'M', 22),
('Chelsea', 'Cesc Fàbregas', 'M', 4),
('Chelsea', 'Eden Hazard', 'M', 10),
('Chelsea', 'Ruben Loftus-Cheek', 'M', 36),
('Chelsea', 'Nemanja Matic', 'M', 21),
('Chelsea', 'John Obi Mikel', 'M', 12),
('Chelsea', 'Kasey Palmer', 'M', 38),
('Chelsea', 'Bertrand Traore', 'M', 14),
('Chelsea', 'Oscar', 'M', 8),
('Chelsea', 'Alexandre Pato', 'F', 11),
('Chelsea', 'Radamel Falcao', 'F', 9),
('Chelsea', 'Kenedy', 'F', 16),
('Chelsea', 'Pedro', 'F', 17),
('Chelsea', 'Loïc Rémy', 'F', 18),
('Chelsea', 'Diego Costa', 'F', 19);

